# Use the official Node image from the Docker Hub
FROM node:22-alpine

# Set the working directory in the container
WORKDIR /app

# Install Node dependencies
COPY package.json package-lock.json* ./
RUN npm ci

# Expose port 3000 for the web server
EXPOSE 3000

# Command to run
CMD ["npm", "start"]